import { ArrowDownRight, ArrowUpRight, Menu, X } from 'lucide-react'
import { useState } from 'react'
import { AudioComparison } from './components/AudioComparison'
import { site } from './data/site'
import './styles.css'

const nav = [['WORK', '#work'], ['SERVICES', '#services'], ['PRICING', '#pricing'], ['ABOUT', '#about'], ['CONTACT', '#contact']]

export default function App() {
  const [open, setOpen] = useState(false)
  return <>
    <header><a className="brand logo-brand" href="#top" aria-label="ADHD Mixing home"><img src={`${import.meta.env.BASE_URL}logo.png`} alt="ADHD Mixing" /></a><nav className={open ? 'open' : ''}>{nav.map(([label, link]) => <a key={label} href={link} onClick={() => setOpen(false)}>{label}</a>)}</nav><button className="menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></header>
    <main id="top">
      <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">{site.hero.eyebrow}</p><h1 id="hero-title">{site.hero.title.split('\n').map((line) => <span key={line}>{line}</span>)}</h1><p className="lede">{site.hero.description}</p><div className="actions"><a className="button lime" href={site.contact.telegram} target="_blank" rel="noreferrer">SEND A MESSAGE <ArrowUpRight size={17} /></a><a className="button text" href="#work">{site.hero.secondaryCta}<ArrowDownRight size={17} /></a></div></div><div className="signal" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><p className="scroll">SCROLL TO LISTEN <span>↓</span></p></section>
      <section id="work" className="work section"><div className="section-head"><p className="index">01 / SELECTED WORK</p><h2>THE PROOF<br/>IS IN THE PLAYBACK.</h2></div><div className="projects">{site.projects.map((project, index) => <article className="project" key={project.title}><div className="project-id">0{index + 1}</div><div className="project-main"><p className="project-meta">{project.artist} <span>—</span> {project.genre}</p><h3>{project.title}</h3><p className="project-copy">{project.description}</p></div><AudioComparison title={project.title} before={project.before} after={project.after} /></article>)}</div></section>
      <section id="services" className="services section"><div className="section-head"><p className="index">02 / WHAT I DO</p><h2>BUILT FOR<br/>THE RECORD.</h2></div><div className="service-grid">{site.services.map((service) => <article key={service.number}><span>{service.number}</span><h3>{service.title}</h3><p>{service.copy}</p></article>)}</div></section>
      <section id="pricing" className="pricing section"><div className="section-head"><p className="index">03 / PRICING</p><h2>NO GUESSWORK.<br/>JUST THE WORK.</h2></div><div className="price-grid">{site.pricing.map((item) => <article className={item.featured ? 'price-card featured' : 'price-card'} key={item.name}>{item.featured && <p className="tag">MOST REQUESTED</p>}<h3>{item.name}</h3><p className="price">{item.price}</p><p className="detail">{item.detail}</p><ul>{item.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><a href={`mailto:${site.contact.email}`} className="card-link">GET STARTED <ArrowUpRight size={16}/></a></article>)}</div></section>
      <section id="about" className="about section"><p className="index">04 / THE ENGINEER</p><div><h2>THE MIX SHOULD<br/>MAKE YOU FEEL<br/>SOMETHING.</h2><p className="about-copy">{site.about.text}</p><dl><div><dt>EXPERIENCE</dt><dd>{site.about.experience}</dd></div><div><dt>CREDITS</dt><dd>{site.about.credits}</dd></div><div><dt>BASED IN</dt><dd>{site.about.location}</dd></div></dl></div></section>
      <section className="process section"><p className="index">05 / HOW IT WORKS</p><div className="steps">{['SEND THE TRACK', 'MIX', 'REVIEW', 'FINAL DELIVERY'].map((step, index) => <div key={step}><span>0{index + 1}</span><p>{step}</p></div>)}</div></section>
      <section id="contact" className="contact"><p className="eyebrow">Ready when you are</p><h2>LET'S MAKE IT<br/>SOUND <em>LIKE A RECORD.</em></h2><a className="contact-link" href={site.contact.telegram} target="_blank" rel="noreferrer">MESSAGE ON TELEGRAM <ArrowUpRight size={25}/></a><div className="contact-links"><a href={site.contact.telegram} target="_blank" rel="noreferrer">TELEGRAM / {site.contact.telegramLabel}</a><a href={`mailto:${site.contact.email}`}>{site.contact.email}</a></div></section>
    </main><footer><img className="footer-logo" src={`${import.meta.env.BASE_URL}logo.png`} alt="ADHD Mixing"/><p>MIXING / VOCAL PRODUCTION / PROJECT MIXING</p><a href={site.contact.telegram} target="_blank" rel="noreferrer">TELEGRAM / {site.contact.telegramLabel} <ArrowUpRight size={13}/></a><a href={site.contact.instagram} target="_blank" rel="noreferrer">{site.contact.instagramLabel} <ArrowUpRight size={13}/></a><a href={`mailto:${site.contact.email}`}>{site.contact.email}</a><p>© 2026 ADHD MIXING</p></footer>
  </>
}
